### PR TITLE
- Added CHANGES file (auto-generated).

### PR DESCRIPTION
**Pull request by manwar**
HI Ari, please review the above change.

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by ajolma** [comment]
How does one update the CHANGES file when making a release? (I guess it is a FAQ, but anyway).

**Comment by Manwar** [comment]
You have two choices:
1) Manually add the change details to the CHANGES file

or

2) Use tool like Dist::Zilla, to automagically update CHANGES file every time you release.

If you opt for #2, I can submit PR with the proposed changes.

Best Regards,
Mohammad S Anwar

**Comment by ajolma** [comment]
There's "svn log >Changes" but that seems quite stupid since if one is really interested then they can simply come to github and see it themselves. And the commit messages are often quite cryptic.

I personally have found very little use for Changes files so I haven't thought so much about them.

But apparently some people use them. There's for example this blog http://blog.urth.org/2011/01/27/changes-file-how-and-how-not-to/

Hm. I'll try to improve this aspect of my modules.

**Comment by ajolma** [comment]
Added now a manual Changes file. Did the same for WFS and will do the same for WMTS.

**Pull request closed without merging**
